### ISSUE TITLE
[FR] Add Piper to TTS_say_Message Blueprint

### ISSUE THREAD

**Issue by fisch55** [SirGoodenough/HA_Blueprints#19]
Hi, is it possible to integrate Piper in your great BluePrint?

Graetz!

**Comment by SirGoodenough** [comment]
I have not set up any of the local voice stuff. Seeing it's the year of the voice, I should probably do this.
No promises, but I will look into it.
Which blueprint would you like me to start with?

**Comment by fisch55** [comment]
I would say you should start with TTS_say_Message Blueprint ! It‘s  great

**Comment by SirGoodenough** [comment]
Want to test this, see if it works?
Never used piler before and some of this was a guess...

IE leaving language and voice empty and hoping it picks up user defaults.

https://github.com/SirGoodenough/HA_Blueprints/blob/Piper_tts_All_Message_Script/Scripts/tts_All_Message_Script_Blueprint.yaml

**Comment by fisch55** [comment]
THX! But I can't choose 
Text to Speech Processor
Required on ALL *_say platforms PIPER?!

**Comment by SirGoodenough** [comment]
Oops, try that

**Comment by fisch55** [comment]
actually it does not work

**Comment by SirGoodenough** [comment]
I also made this one that was nabu-casa only before also do Piper...

https://github.com/SirGoodenough/HA_Blueprints/blob/Piper_tts_All_Message_Script/Automations/door_open_tts_cloud_say_announcer_nabu_casa_required.yaml

**Comment by SirGoodenough** [comment]
Probably going to release this in a day or 2.
If you see any Bugs, please let me know.

**Comment by fisch55** [comment]
Thx , I‘ll try it later 👍

**Comment by SirGoodenough** [comment]
Closed by PR #20
