### ISSUE TITLE
[FR] Magic Cube Pro - Flip to side X action

### ISSUE THREAD

**Issue by TimBroddin** [SirGoodenough/HA_Blueprints#22]
**Which Blueprint is This Concern About / Related To?**
[🧯 Zigbee2MQTT Aqara Magic Cube T1-Pro CTP-R01 Xiaomi Lumi ](https://community.home-assistant.io/t/zigbee2mqtt-aqara-magic-cube-t1-pro-ctp-r01-xiaomi-lumi-cagl02/525111/59)

**Is your feature request related to a problem? Please describe.**
I'd like to be able to trigger an action when I move the dice to a side. Just have a “Flip to side 1” action instead of 5 actions.

**Describe the solution you'd like**
6 news actions: Flip to side 1, 2, 3, 4, 5 and 6.

**Describe alternatives you've considered**
I've tried adding them 6 times each, but this doesn't help maintainability on the user's end.

**Comment by SirGoodenough** [comment]
@TimBroddin , I am working on this.
However if you switch your cube to scene mode, there is a set of flip to side 1, 2, 3, 4, 5, or 6 from any already. I had added it and didn't remember.
I will be adding the same to the action mode as the next release.

**Comment by TimBroddin** [comment]
I can't seem to find them 🫠 I've double checked and I'm on the latest version. All I see are the individual "flip to side 1 from side X":

![CleanShot 2023-10-13 at 16 09 46@2x](https://github.com/SirGoodenough/HA_Blueprints/assets/528287/fdd2b92b-5173-4f86-b765-def93faaac59)

Thanks for your effort!

**Comment by SirGoodenough** [comment]
They are misleadingly labeled, which s also being fixed, but the Group 1 flips are flip from any to the labeled side.

![Screenshot_20231013_203306](https://github.com/SirGoodenough/HA_Blueprints/assets/47349533/40875333-8e97-4dc8-9173-ac2031169233)

**Comment by SirGoodenough** [comment]
Updated to all 3 cube BP's to add functionality.

**Comment by TimBroddin** [comment]
Thanks a lot @SirGoodenough 🙏 I had testing this on my todo list for the past week, but didn't get around to it. Keep up the great work, much appreciated.
