### ISSUE TITLE
extended example on colorchange script aqara cube

### ISSUE THREAD

**Issue by ivo1981** [SirGoodenough/HA_Blueprints#3]
Can you provide a more complete example on the color change section please?
If i copy paste it in an empty script it generates errors. 
This is probably very logical but i can't figure out how to use it.
thanks a lot by the way for this addon!

**Comment by SirGoodenough** [comment]
I'm terribly sorry I missed this issue.
I just got back into town.
Anyway you can see my working copy in my personal configuration.
The Script where the color change is located:
https://github.com/SirGoodenough/Home-Assistant-Config/blob/master/script2/cube_script.yaml

And the Automation calling the blueprint.
https://github.com/SirGoodenough/Home-Assistant-Config/blob/master/automation2/Z2M-Xiaomi_Cube_A2.yaml

**Comment by SirGoodenough** [comment]
close
