### ISSUE TITLE
[BUG] action that calls an unknown service

### ISSUE THREAD

**Issue by ThetomekK** [SirGoodenough/HA_Blueprints#31]
Hi,
i am sorry to bother you, but i can't get the dimmer control to work. Following error occurs:
![image](https://github.com/SirGoodenough/HA_Blueprints/assets/6866371/f7bfe380-3454-4441-9c6c-4d6d56784047)

the scripts part:
![image](https://github.com/SirGoodenough/HA_Blueprints/assets/6866371/72ea3cac-9dc1-47cc-8180-7b39a42bdae2)

and the actions in the automation:
![image](https://github.com/SirGoodenough/HA_Blueprints/assets/6866371/e4cf054e-6f11-4aee-ac53-ea8acace83b2)

All parts were just copy & pasted, no personal adoptions.

Other stuff like tapping sides to turn on/off the selected light work porperly.
Do you have an idea, what is going wrong?

**Comment by SirGoodenough** [comment]
Couple of things.  

Where did you put the cube dimmer script in the configuration, under what integration?
It doesn't look like it was identified as a script...

Since I wrote the script blueprints that handle the dimmer and the rest of the addons I have been ignoring the manually added ones.  The script blueprint for dimmer now has a transition component should you want to use it.  I suggest just installing that, it takes care of the installation for you.

My next edit will probably be to remove the manually added scripts in favor of the blueprint versions.

**Comment by ThetomekK** [comment]
Hi, 
thanks for your reply. I added the cube dimmer script directly in my scripts.yaml.
Next i tried to add the script part through out the blueprint, thats what i did:
Import the script blueprint:
![image](https://github.com/SirGoodenough/HA_Blueprints/assets/6866371/89e71de6-b942-42fa-8685-a4d09d26a616)
Add the script:
![image](https://github.com/SirGoodenough/HA_Blueprints/assets/6866371/8263990c-5358-44b0-8c01-518f58dd8ea6)
![image](https://github.com/SirGoodenough/HA_Blueprints/assets/6866371/ab2dd671-9a06-42bb-ab94-858978ba2c9b)
Script is added to the scripts.yaml
![image](https://github.com/SirGoodenough/HA_Blueprints/assets/6866371/92ac861d-bc85-40cc-bbf8-257ce9e72c27)
However it is not listed in the script tab (is that behavior intended?)
![image](https://github.com/SirGoodenough/HA_Blueprints/assets/6866371/e0a82f93-f418-446d-ab0f-1a7f58610ca6)
Now in the device itself:
![image](https://github.com/SirGoodenough/HA_Blueprints/assets/6866371/1185b3f5-7afb-4848-866e-f45905b5a1fd)
i add this:
![image](https://github.com/SirGoodenough/HA_Blueprints/assets/6866371/3d41e9ec-ba28-44dd-a1ae-58d2a3cd3196)
the automation tells me:
![image](https://github.com/SirGoodenough/HA_Blueprints/assets/6866371/15cb0c9c-3f1d-49ca-9b1e-0fae1d4d370e)
with no success

**Comment by SirGoodenough** [comment]
After you import the dimmer blueprint, you must create the script based on that blueprint using the script editor create script window I see above. The blueprint itself doesn't do anything, needs a script to call it.
Did you do that.

**Comment by SirGoodenough** [comment]
This is clearly not a bug.  Helping yopu thru this issue would clearly help others.  Can we continue this in the exchange post where others would see the process?
https://community.home-assistant.io/t/miscellaneous-blueprint-scripts-volume-dimming-reset-long-short-press-simulation-color-change/602059

**Comment by ThetomekK** [comment]
yes, of course!

**Comment by ThetomekK** [comment]
Hi,
just got it to work. Mistake was on my side (well that is actually no suprise).
in my configuration.yaml the part script: !include scripts.yaml was uncomment.
And this explains why the very first error occured:

![image](https://github.com/SirGoodenough/HA_Blueprints/assets/6866371/4496d03a-937c-498f-99b3-fede2641825c)

So your blueprints and the installation procedure are clear.
Thanks a lot for your work at all.
BR
