### ISSUE TITLE
warning: 'dict object' has no attribute[BUG] 

### ISSUE THREAD

**Issue by enrawi** [SirGoodenough/HA_Blueprints#32]
Blueprint: Aqara Magic Cube Zigbee2MQTT MQTT Triggered - 2023-10-20
get this every time i use the cube.
Template variable warning: 'dict object' has no attribute 'operation_mode' when rendering '{{ trigger.payload_json.operation_mode }}'

**Comment by SirGoodenough** [comment]
It would help if you followed the issue template here a little.
I need your automation code so i can see what is broken.
An answer of it works for everyone else is not what you want to hear but without that, it's all I got.

I would guess / suspect one of 3 things.  The beginning part of the setup regarding legacy in the set-up is not set-up to match the blueprint, or there is a problem with templates that you are calling with actions, or you have zombie versions of the blueprint running and triggering where you tried and failed to get it running, but did not remove them, so they still run every time you trigger it.

**Comment by enrawi** [comment]
Sorry. whas hard to copy all on phone.
Im not using it for mutch. just to toggle 1 light and dim it up and down.
`trigger:
  - platform: mqtt
    topic: zigbee2mqtt/AqaraCube
variables:
  action: '{{ trigger.payload_json.action }}'
  angle: '{{ trigger.payload_json.action_angle | float(0.0) }}'
  side: '{{ trigger.payload_json.side }}'
  op_mode: '{{ trigger.payload_json.operation_mode }}'
  topic_var: zigbee2mqtt/AqaraCube
  friendly_name: '{{ topic_var.split(''/'')[1] | regex_replace("[^A-Za-z0-9_/./-]", "") }}'
  device_id: '{{ device_id( friendly_name ) }}'
  ieee_id_long: '{{(( device_attr( device_id, ''identifiers'') |list)[0][1]) }}'
  ieee_id: '{{ieee_id_long.split(''_'')[1] }}'
  num_name: last side
  num_ha_name: '{{ ''number.'' + friendly_name + ''_last_side'' }}'
  num_ha_val: '{{ states(num_ha_name) | default(0) | int(0) }}'
  last_side: ' {# The first time it will not be there, so make sure its 0 instead of undefined. #} {% if not num_ha_val in (''none'', ''null'', ''unavailable'', '''') %} {{ num_ha_val }} {% else %} 0 {% endif %}'
  mdl: Number Helper for Z2M Cube Integration
  mf: SirGoodenough
  sa: house
  sw: '2023-10-20'
  hw: >-
    https://github.com/SirGoodenough/HA_Blueprints/blob/master/Automations/Zigbee2MQTT
    - Xiaomi Cube Controller.yaml
  cu: >-
    https://community.home-assistant.io/t/zigbee2mqtt-xiaomi-cube-controller/393203
  config_topic_2: '{{ ''homeassistant/number/'' + ieee_id + ''/last_side/config'' }}'
  topic_2: '{{ ''homeassistant/number/'' + ieee_id + ''/last_side'' }}'
condition:
  - condition: template
    value_template: >-
      {{ trigger.payload_json is defined and trigger.payload_json.action is
      defined and trigger.payload_json.action in ('rotate_right', 'rotate_left',
      'flip90', 'flip180', 'slide', 'tap', 'shake', 'fall') }}
  - alias: User pick
    condition: []
action:
  - alias: Make number helper to store last side
    service: mqtt.publish
    data:
      topic: '{{ config_topic_2 }}'
      retain: true
      payload: |
        { "name": "{{ num_name }}",
          "avty_t": "homeassistant/status",
          "uniq_id": "{{ friendly_name + '-' + device_id }}",
          "cmd_t": "{{ topic_2 }}",
          "sta_t": "{{ topic_2 }}",
          "min": "0",
          "max": "6",
          "step": "1",
          "mode": "box",
          "ret": true,
          "dev": {
            "name": "{{ friendly_name }}",
            "mdl": "{{ mdl }}",
            "mf": "{{ mf }}",
            "sa": "{{ sa }}",
            "sw": "{{ sw }}",
            "hw": "{{ hw }}",
            "cu": "{{ cu }}",
            "ids": [
              "{{ ieee_id + '-' + num_name }}"
            ]
          }
        }
  - alias: Fire Last Action event. This is for optional troubleshooting data.
    event: cube_last_action
    event_data:
      action: '{{ action }}'
      side: '{{ side }}'
      last_side: '{{ last_side }}'
      friendly_name: '{{ friendly_name }}'
      device_id: '{{ device_id }}'
      ieee_id: '{{ ieee_id }}'
      angle: '{{ angle }}'
  - alias: Store the current_side as the last_side for the next trigger
    service: number.set_value
    target:
      entity_id: '{{ num_ha_name }}'
    data:
      value: '{{ side }}'
  - alias: Group 2 🍊 and No Group 🍩 These are action events for ANY Side
    choose:
      - conditions: '{{ action == "slide" }}'
        sequence: []
      - conditions: '{{ action == "tap" }}'
        sequence: []
      - conditions: '{{ action == "rotate_right" }}'
        sequence: []
      - conditions: '{{ action == "rotate_left" }}'
        sequence: []
      - conditions: '{{ action == "shake" }}'
        sequence: []
      - conditions: '{{ action == "fall" }}'
        sequence: []
      - conditions: '{{ action == "flip90" }}'
        sequence:
          - parallel:
              - []
              - alias: These are flip to specific side from any side events
                choose:
                  - conditions: '{{ side == 0 }}'
                    sequence: []
                  - conditions: '{{ side == 1 }}'
                    sequence: []
                  - conditions: '{{ side == 2 }}'
                    sequence: []
                  - conditions: '{{ side == 3 }}'
                    sequence: []
                  - conditions: '{{ side == 4 }}'
                    sequence: []
                  - conditions: '{{ side == 5 }}'
                    sequence: []
      - conditions: '{{ action == "flip180" }}'
        sequence:
          - parallel:
              - []
              - alias: These are flip to specific side from any side events
                choose:
                  - conditions: '{{ side == 0 }}'
                    sequence: []
                  - conditions: '{{ side == 1 }}'
                    sequence: []
                  - conditions: '{{ side == 2 }}'
                    sequence: []
                  - conditions: '{{ side == 3 }}'
                    sequence: []
                  - conditions: '{{ side == 4 }}'
                    sequence: []
                  - conditions: '{{ side == 5 }}'
                    sequence: []
  - alias: Group 1 🍎 These are action events based on the action broken down by side
    choose:
      - conditions: '{{ action == "slide" }}'
        sequence:
          - alias: These are slide events
            choose:
              - conditions: '{{ side == 0 }}'
                sequence: []
              - conditions: '{{ side == 1 }}'
                sequence: []
              - conditions: '{{ side == 2 }}'
                sequence: []
              - conditions: '{{ side == 3 }}'
                sequence: []
              - conditions: '{{ side == 4 }}'
                sequence: []
              - conditions: '{{ side == 5 }}'
                sequence: []
      - conditions: '{{ action == "tap" }}'
        sequence:
          - alias: These are doubletap events
            choose:
              - conditions: '{{ side == 0 }}'
                sequence:
                  - service: light.toggle
                    data:
                      brightness_pct: 50
                    target:
                      entity_id: light.spotter_kjeller
              - conditions: '{{ side == 1 }}'
                sequence: []
              - conditions: '{{ side == 2 }}'
                sequence: []
              - conditions: '{{ side == 3 }}'
                sequence: []
              - conditions: '{{ side == 4 }}'
                sequence: []
              - conditions: '{{ side == 5 }}'
                sequence: []
      - conditions: '{{ action == "flip90" }}'
        sequence:
          - alias: These are flipped90 events
            choose:
              - conditions: '{{ side == 0 }}'
                sequence: []
              - conditions: '{{ side == 1 }}'
                sequence: []
              - conditions: '{{ side == 2 }}'
                sequence: []
              - conditions: '{{ side == 3 }}'
                sequence: []
              - conditions: '{{ side == 4 }}'
                sequence: []
              - conditions: '{{ side == 5 }}'
                sequence: []
      - conditions: '{{ action == "flip180" }}'
        sequence:
          - alias: These are flipped180 events
            choose:
              - conditions: '{{ side == 0 }}'
                sequence: []
              - conditions: '{{ side == 1 }}'
                sequence: []
              - conditions: '{{ side == 2 }}'
                sequence: []
              - conditions: '{{ side == 3 }}'
                sequence: []
              - conditions: '{{ side == 4 }}'
                sequence: []
              - conditions: '{{ side == 5 }}'
                sequence: []
      - conditions: '{{ action == "rotate_right" }}'
        sequence:
          - alias: These are rotate CW events
            choose:
              - conditions: '{{ side == 0 }}'
                sequence:
                  - service: light.turn_on
                    data:
                      brightness_step_pct: 5
                    target:
                      entity_id: light.spotter_kjeller
              - conditions: '{{ side == 1 }}'
                sequence: []
              - conditions: '{{ side == 2 }}'
                sequence: []
              - conditions: '{{ side == 3 }}'
                sequence: []
              - conditions: '{{ side == 4 }}'
                sequence: []
              - conditions: '{{ side == 5 }}'
                sequence: []
      - conditions: '{{ action == "rotate_left" }}'
        sequence:
          - alias: These are rotate CCW events
            choose:
              - conditions: '{{ side == 0 }}'
                sequence:
                  - service: light.turn_on
                    data:
                      brightness_step_pct: -5
                    target:
                      entity_id: light.spotter_kjeller
              - conditions: '{{ side == 1 }}'
                sequence: []
              - conditions: '{{ side == 2 }}'
                sequence: []
              - conditions: '{{ side == 3 }}'
                sequence: []
              - conditions: '{{ side == 4 }}'
                sequence: []
              - conditions: '{{ side == 5 }}'
                sequence: []
  - alias: Group 3 🍐 Side to side jump events
    choose:
      - conditions: '{{ side == 0 }}'
        sequence:
          - alias: To side 0 from any events
            choose:
              - conditions: '{{ last_side == 1 }}'
                sequence: []
              - conditions: '{{ last_side == 2 }}'
                sequence: []
              - conditions: '{{ last_side == 3 }}'
                sequence: []
              - conditions: '{{ last_side == 4 }}'
                sequence: []
              - conditions: '{{ last_side == 5 }}'
                sequence: []
      - conditions: '{{ side == 1 }}'
        sequence:
          - alias: To side 1 from any events
            choose:
              - conditions: '{{ last_side == 0 }}'
                sequence: []
              - conditions: '{{ last_side == 2 }}'
                sequence: []
              - conditions: '{{ last_side == 3 }}'
                sequence: []
              - conditions: '{{ last_side == 4 }}'
                sequence: []
              - conditions: '{{ last_side == 5 }}'
                sequence: []
      - conditions: '{{ side == 2 }}'
        sequence:
          - alias: To side 2 from any events
            choose:
              - conditions: '{{ last_side == 0 }}'
                sequence: []
              - conditions: '{{ last_side == 1 }}'
                sequence: []
              - conditions: '{{ last_side == 3 }}'
                sequence: []
              - conditions: '{{ last_side == 4 }}'
                sequence: []
              - conditions: '{{ last_side == 5 }}'
                sequence: []
      - conditions: '{{ side == 3 }}'
        sequence:
          - alias: To side 3 from any events
            choose:
              - conditions: '{{ last_side == 0 }}'
                sequence: []
              - conditions: '{{ last_side == 1 }}'
                sequence: []
              - conditions: '{{ last_side == 2 }}'
                sequence: []
              - conditions: '{{ last_side == 4 }}'
                sequence: []
              - conditions: '{{ last_side == 5 }}'
                sequence: []
      - conditions: '{{ side == 4 }}'
        sequence:
          - alias: To side 4 from any events
            choose:
              - conditions: '{{ last_side == 0 }}'
                sequence: []
              - conditions: '{{ last_side == 1 }}'
                sequence: []
              - conditions: '{{ last_side == 2 }}'
                sequence: []
              - conditions: '{{ last_side == 3 }}'
                sequence: []
              - conditions: '{{ last_side == 5 }}'
                sequence: []
      - conditions: '{{ side == 5 }}'
        sequence:
          - alias: To side 5 from any events
            choose:
              - conditions: '{{ last_side == 0 }}'
                sequence: []
              - conditions: '{{ last_side == 1 }}'
                sequence: []
              - conditions: '{{ last_side == 2 }}'
                sequence: []
              - conditions: '{{ last_side == 3 }}'
                sequence: []
              - conditions: '{{ last_side == 4 }}'
                sequence: []
  - alias: >-
      Delay ⏱ for debounce so toggle functions work. Also blueprint is in single
      mode.
    delay: '00:00:01'
mode: single
max_exceeded: silent
id: '1701534676889'
alias: Aqara Magic Cube Zigbee2MQTT MQTT Triggered - 2023-10-20
description: ''`

**Comment by SirGoodenough** [comment]
That appears to be the blueprint, which is my code. I already have that.  I need the automation you added to call the blueprint.  That is your part of the code.
Should look similar to this///
```yaml
- id: "12a989e7-9606-41e6-82fb-fed4fad6e5d3"
  alias: Yertle Cube
  description: All the things Yertle can do
  trace:
    stored_traces: 10
  use_blueprint:
    path: SirGoodenough/Zigbee2MQTT-Xiaomi_Cube_Controller_MQTT_Triggered.yaml
    input:
      topic: zigbee2mqtt/Yertle
      fall:
        - type: turn_on
          device_id: d99723186c9d0c8de8475bf9646b8373
          entity_id: switch.plug2
          domain: switch
      doubletap_face_0:
        - service: light.toggle
          entity_id: light.grp_kitch
      rotate_cw_face_0:
        - service: script.cube_dimmer_control_bp
          data:
            angle: '{{ trigger.payload_json.action_angle | float(0.0) }}'
            light: light.grp_kitch
      rotate_ccw_face_0:
        - service: script.cube_dimmer_control_bp
          data:
            angle: '{{ trigger.payload_json.action_angle | float(0.0) }}'
            light: light.grp_kitch
```

**Comment by enrawi** [comment]
It whas the full automation config.
this is my config only.
`id: '1701534676889'
alias: Aqara Magic Cube Zigbee2MQTT MQTT Triggered - 2023-10-20
description: ''
use_blueprint:
  path: SirGoodenough/Zigbee2MQTT-Xiaomi_Cube_Controller_MQTT_Triggered.yaml
  input:
    topic: zigbee2mqtt/AqaraCube
    doubletap_face_0:
      - service: light.toggle
        data:
          brightness_pct: 50
        target:
          entity_id: light.spotter_kjeller
    rotate_cw_face_0:
      - service: light.turn_on
        data:
          brightness_step_pct: 5
        target:
          entity_id: light.spotter_kjeller
    rotate_ccw_face_0:
      - service: light.turn_on
        data:
          brightness_step_pct: -5
        target:
          entity_id: light.spotter_kjeller`

**Comment by SirGoodenough** [comment]
PR #34 
Update about8 blueprints to fix issues related to the bug.
Thanks @enrawi for pointing out the problem.
They should all be fixed now.

So this touches a few blueprints, but doesn’t change any function. I suggest you use the new [re-download feature of Home Assistant](https://www.home-assistant.io/blog/2023/12/06/release-202312/#re-import-blueprints), however, and replace them now. Then your logs will be free of the spamming some of the older versions did.

**Comment by enrawi** [comment]
Thx for fixing this :)
