### ISSUE TITLE
HA_Blueprints/Automations /Zigbee2MQTT-Aqara-Magic-Cube-T1-Pro-CTP-R01-Xiaomi-Lumi.md

### ISSUE THREAD

**Issue by Lesboy72** [SirGoodenough/HA_Blueprints#36]
HA_Blueprints/Automations
/Zigbee2MQTT-Aqara-Magic-Cube-T1-Pro-CTP-R01-Xiaomi-Lumi.md

Hi, I have installed the subject Blueprint. I enter a trial automatism as in the picture, if I run it next to the specified part, it works. In the drop-down menu in the upper right corner of the screen, I don't think the run anymore works.
Last run indicates that it has never been run before and cannot be run manually. If I create automation with the cube elsewhere, either with the controlled device or with MQTT, it works. But the opportunity is much more than your development, which is why I insist on you. Thank you for looking at it: László
![aqara](https://github.com/SirGoodenough/HA_Blueprints/assets/101478461/fa4851de-0853-4d1e-96e2-4571e527bc27)
![aqara2](https://github.com/SirGoodenough/HA_Blueprints/assets/101478461/7bb9a57e-a511-46d4-93bf-c74c7a03bc8b)
![aqara3](https://github.com/SirGoodenough/HA_Blueprints/assets/101478461/f5adf15f-9afb-46c2-8b1b-9e24ea9ebcb7)

**Comment by SirGoodenough** [comment]
I see your screenshots of the automation UI and those are no help to me. I don't have any idea what is going on.
The text in the top of the bug report needs to be filled in where appropriate.  Don't have to fill them all in, but giving me YAML to troubleshoot and versions of things are needed.

Google Translate to help you out...

A Google Fordító segít...

Látom az automatizálási felhasználói felületről készült képernyőképeit, és ezek nem segítenek nekem. Fogalmam sincs, mi folyik itt.
A hibajelentés tetején található szöveget ki kell tölteni, ahol szükséges. Nem kell mindet kitölteni, de a YAML-t megadom a hibaelhárításhoz, és szükség van a dolgok verziójára.

**Alapszabályok**
Mielőtt jelentene egy „Hibát”, győződjön meg arról, hogy teljesen elolvasta a mellékelt *.md fájlt vagy a Community Exchange bejegyzés főfájlját, és követte az ott előírt összes beállítást.
Ez azért fontos, mert ha nem tartják be ezeket az utasításokat, valószínűleg rossz napja lesz, és kénytelen lesz felvenni velem a kapcsolatot segítségért. Nem mintha nem akarok segíteni, de a személyes interakció eltart egy ideig, amíg válaszolok, és általában nem produktív.

A problémák nem helye a kérdések feltevésének, ehhez tekintse meg az alábbi Discord-linkeket. Ez a törött dolgokra való. Ha nem vagy biztos benne, KÉRJÜK, menj a Discord oldalra, és először tedd fel a kérdést.

Ha van általános kérdése, szívesebben teszem fel a Discordon. Pingelj a csatornán, nem gyakran válaszolok a DM-ekre... @sirgoodenough

Figyelemmel kísérem az egyes Blueprintekhez kapcsolódó Blueprint Exchange-bejegyzéseket is, és ott válaszolok.

A Discordon 3 helyet figyelek, preferenciális sorrendben:

Személyes Discord Blueprints csatornám: https://discord.gg/HwFKS4my8Y
DrZzs Blueprint csatorna: https://discord.gg/jvk7yEFyX3
Homa Assistant Blueprint Channel: https://discord.gg/jPPvqsWwzh

Ha úgy gondolja, hogy hibát talált, ahol a szöveg rosszra mutat, vagy valami elromlott, folytassa itt. Ha szolgáltatáskérelme van, tekintse meg a másik problémasablont...

**Melyik tervvel kapcsolatos/amelyhez kapcsolódik?**
Link vagy a Blueprint neve.

**Írja le a hibát**
Világos és tömör leírás arról, hogy mi a hiba.

**Reprodukció**
A viselkedés reprodukálásának lépései:
1. Lépjen a "..." elemre
2. Kattintson a "...."
3. Görgessen le a '....'
4. Lásd a hibát

**Elvárt viselkedés**
Világos és tömör leírás arról, hogy mire számítottál.

**Képernyőképek**
Ha lehetséges, adjon hozzá képernyőképeket a probléma magyarázatához.

**A tervrajz melyik verziójában van a probléma?**
(A Tervrajz címe tartalmazza a revíziót.)
[![Nyissa meg a Home Assistant példányát, és mutassa meg tervrajzait.](https://my.home-assistant.io/badges/blueprints.svg)](https://my.home-assistant.io/redirect/blueprints /)

**Mi volt a Home Assistant Core verziója?**
[![Nyissa meg a Home Assistant-példányt, és jelenítse meg a rendszer állapotára vonatkozó információkat.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/ redirect/system_health/)

**Milyen típusú telepítést futtat?**
[![Nyissa meg a Home Assistant-példányt, és jelenítse meg a rendszer állapotára vonatkozó információkat.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/ redirect/system_health/)

**YAML-részletek, BELEÉRTVE a forgatókönyvet vagy az automatizálást, amelyet a terv meghívására építettél**
(Használjon 3 backtick-et a kód előtt és után a megfelelő formázáshoz)
Lásd például itt: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**További kontextus**
Adjon hozzá bármilyen más kontextust a problémával kapcsolatban.

**Comment by SirGoodenough** [comment]
Reading your question more, the 'run' in the ui editor isn't going to do anything here, because the blueprint is looking for changes in the cube to trigger events.  When you click the 'run', there wasn't a cube action so it will do nothing. 

You have to do cube actions to make the blueprint trigger and execute the actions you have programed in.

**Comment by SirGoodenough** [comment]
I'm trying to explain to you how this works.
If you click the run command, the blueprint does indeed run.
As the BP starts it gets to the condition statement which makes sure that the trigger that started the run has a valid action from the cube.  When it finds there was no action, execution ends.
So yes, it runs, but no, it stops as soon as conditions are tested.

**Comment by Lesboy72** [comment]
Thank you for the previous ones as well. Let's go on. Now I only have two questions, because I don't have the dice in front of me right now, I'm not at home, only in the evening.
One: Should I write something here? I think not. 
![aqara4](https://github.com/SirGoodenough/HA_Blueprints/assets/101478461/90dbb4bc-970a-497e-9a21-6d5fbd2d10e5)

According to your previous answer, a condition must be entered here? I think you don't have to.
![aqara5](https://github.com/SirGoodenough/HA_Blueprints/assets/101478461/1e5db3ee-4553-436e-ae0b-210267d29a4b)

**Comment by SirGoodenough** [comment]
Did you read the instructions?
These are in a TL;DR version in the blueprint description and the long version [here](https://github.com/SirGoodenough/HA_Blueprints/blob/master/Automations/Zigbee2MQTT-Aqara-Magic-Cube-T1-Pro-CTP-R01-Xiaomi-Lumi.md).

1. For the first question, if you don't have a topic, nothing will happen.  The blueprint will get no data to do anything.
2. For the 2nd question you add actions in the rows to match the physical actions you do with the cube.

Start with no automations created with the blueprint.  If you have old ones hanging around they will start to trigger and it will confuse you.  Then create an automation with a simple event, like rotate or slide, ant just toggle a light.  This gets you into the mode of how it works.  Then using the training aids provided, learn how the other functions like tap and hold, etc work.

All this is in the documentation.

**Comment by Lesboy72** [comment]
It would be great if you had a YouTube video about this installation, setup, and operation. Believe me, everyone would be happy about it, and it wouldn't take you so long to do this :) At stake, if I make settings by default, they work. I can't get your BP to work.

**Comment by SirGoodenough** [comment]
That has been on my mind lately for all my blueprints...
Excellent suggestion.
I am working on the clean the basement stuff first because I have a real problem down there.

Have you determined what your topic is yet?

**Comment by Lesboy72** [comment]
I do not understand. What about the topic?

**Comment by SirGoodenough** [comment]
> One: Should I write something here? I think not.
> ![aqara4](https://private-user-images.githubusercontent.com/101478461/308857465-90dbb4bc-970a-497e-9a21-6d5fbd2d10e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNDg5MTUsIm5iZiI6MTcwOTM0ODYxNSwicGF0aCI6Ii8xMDE0Nzg0NjEvMzA4ODU3NDY1LTkwZGJiNGJjLTk3MGEtNDk3ZS05YTIxLTZkNWZiZDJkMTBlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQwMzAzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjhiOWU4N2M0Yzk5NWY2OTZjZGVlYmE4NGM4ZjgxNTA4OGU4YTkyN2IxYmY2YzMxMGZlMWRjZGIyOTA5MjdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8h-1NWvzfhzv8KduksD572UFiZbtFg6HCANgaT9V82s)

**Comment by Lesboy72** [comment]
I gave the topic. The trace path shows this, somewhere (perhaps under a condition) the run gets stuck and stops. What can I send you so that you can help me?


![cub1](https://github.com/SirGoodenough/HA_Blueprints/assets/101478461/49401025-cd10-4b05-9a59-40a48b2ec0ee)

**Comment by SirGoodenough** [comment]
As the Docs say, the last action Z2M takes is not going to pass conditions.  Look at prior triggers in the list to see if it did anything.  There is nearly always minimum 3 triggers on any physical action.  wake-up, the actual action, and go to sleep.

**Comment by Lesboy72** [comment]
If I perform a cube operation (**now the operation works fine**), for example, I slide, then a device under your name and house location will immediately appear. When I open the following image I see. What is it and why does it occur? Is that okay?

![cube1](https://github.com/SirGoodenough/HA_Blueprints/assets/101478461/f6cd5600-7c5e-4593-969f-c1576de84861)
![cube2](https://github.com/SirGoodenough/HA_Blueprints/assets/101478461/c3879945-5d28-46b0-abc1-967e378a55e2)

**Comment by SirGoodenough** [comment]
It creates a number entity to keep track of the last side that was on top. Yes it creates that and will update the number value whenever you action the cube.
This is good news.  It means things are starting to work for you!

**Comment by SirGoodenough** [comment]
Stale
