### ISSUE TITLE
Shake not working

### ISSUE THREAD

**Issue by p3t3r** [SirGoodenough/HA_Blueprints#4]
Hello,
I'm trying a simple action (shake) to trigger a scene, but it's not working.

id: '1657894243328'
alias: Aqara Magic Cube Zigbee2MQTT - 2022-05-05
description: ''
use_blueprint:
  path: SirGoodenough/Zigbee2MQTT - Xiaomi Cube Controller.yaml
  input:
    shake:
      - service: scene.turn_on
        target:
          entity_id: scene.zolder_zolder_oranje
        metadata: {}
    remote: sensor.aqara_cube_action
    
The trace timeline shows:
Triggered by the state of sensor.aqara_cube_action at July 15, 2022 at 4:22:26 PM
Test template condition
Stopped because a condition failed at July 15, 2022 at 4:22:26 PM (runtime: 0.00 seconds)

**Comment by SirGoodenough** [comment]
Is all this correct?
https://github.com/SirGoodenough/HA_Blueprints/blob/master/Automations/Zigbee2MQTT%20-%20Xiaomi%20Cube%20Controller.md#-to-make-the-blueprint-work-it-will-need

**Comment by p3t3r** [comment]
Thanks for the reply. 
I did see the '''sensor.xxDevice_Namexx_action''', but I changed the legay settings anyway and after that it worked.

**Comment by SirGoodenough** [comment]
Glad you got it working.
